### ISSUE TITLE
Release - 1.2.4 Update

### ISSUE THREAD

**Issue by heonha** [heonha/koget-ios#32]
- [x] 메인 / 설정화면 UI 개선 #25
- [x] 메인화면 아이콘 재배치 #25 
- [x] 위젯 만들기 UI / UX 개선  #25  
- [x] #33
- [x] 앱스토어 릴리즈용 소개이미지 작성
- [x] 심사 제출
- [x] 심사 승인

**Comment by heonha** [comment]
https://github.com/heonha/koget-ios/releases/tag/1.2.4.1
